name: Reusable Pulumi Workflow

on:
  workflow_call:
    inputs:
      stack-name:
        description: 'The name of the stack to operate on'
        required: true
        type: string
    secrets:
      pulumi-access-token:
        description: 'The Pulumi access token to use'
        required: true
      civo-token:
        description: 'The Civo token to use'
        required: true
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
      - uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f # v3.3.1
        with:
          go-version: 1.19
      - run: go mod download
      - run: go run .
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.pulumi-access-token }}
          CIVO_TOKEN: ${{ secrets.civo-token }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMENT_ON_PR: true

